# Generated by Django 6.0 on 2025-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_dolar',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Base para BS ($)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Cash/Zelle ($)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tasa_dolar',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
