# Generated by Django 6.0 on 2025-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_costo_remove_producto_precio_dolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_base_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
