# Generated by Django 6.0 on 2025-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_precio_base_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tasa_euro',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
