# Generated by Django 6.0 on 2025-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_configuracion_tasa_euro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('anio_inicio', models.IntegerField()),
                ('anio_fin', models.CharField(max_length=10)),
                ('filtro_aceite', models.CharField(blank=True, max_length=50, null=True)),
                ('filtro_aire', models.CharField(blank=True, max_length=50, null=True)),
                ('filtro_combustible', models.CharField(blank=True, max_length=50, null=True)),
                ('filtro_cabina', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
